# Example configuration for Timevault.
# Backup disks are enrolled by filesystem UUID and stay offline by default.

mountBase: "/run/timevault/mounts"
userMountBase: "/run/timevault/user-mounts"
backupDisks:
  - diskId: "primary"
    fsUuid: "REPLACE-WITH-UUID"
    label: "primary-backup"
    mountOptions: "rw,nodev,nosuid,noexec"

excludes:
  - "/proc"
  - "/sys"
  - "/dev"
  - "/run"
  - "/tmp"
  - "/var/tmp"
  - "/var/cache"
  - "/mnt"

jobs:
  - name: "etc-snapshots"
    source: "/etc"
    copies: 14
    run: "demand"
    excludes: []
  - name: "home-weekly"
    source: "/home"
    copies: 8
    run: "auto"
    excludes:
      - "/home/*/.cache"
