# mount is required for all jobs; .timevault must exist at the mount root.
# mount points must be present in /etc/fstab.
# job run policy: auto | demand | off
mount_prefix: "/mnt/backup/"
excludes:
  - "/backups"
  - "/proc"
  - "/var/run"
  - "/var/log"
  - "/var/tmp"
  - "/tmp"
  - "/mnt"
  - "/net"
  - "/dev"
  - "/initrd"
  - "/var/lib/imap/proc"
  - "/var/spool/postfix/active"
  - "/var/spool/postfix/defer"
  - "/var/spool/postfix/deferred"
  - "/var/spool/postfix/maildrop"
  - "/var/spool/squid"
  - "/var/cache"
  - "/sys"
  - "/data/docker"
  - "/data/mirrors"
  - "/data/swapfile"
  - "/data/venomsoft"
  - "/data/pub/backups"
  - "/media"
  - ".thumbnails"
  - "/run"
  - "/root/tmp"

jobs:
  - name: "spitfire-primary"
    source: "/"
    dest: "/mnt/backup/1/dublinux"
    copies: 30
    mount: "/mnt/backup/1"
    run: "auto"
    depends_on: []
    excludes: []
  - name: "bf109-primary"
    source: "root@mail.moyville.net:/"
    dest: "/mnt/backup/1/bf109"
    copies: 30
    mount: "/mnt/backup/1"
    run: "auto"
    depends_on: []
    excludes: []
  - name: "spitfire-secondary"
    source: "/mnt/backup/1/dublinux/current/"
    dest: "/mnt/backup/2/dublinux"
    copies: 30
    mount: "/mnt/backup/2"
    run: "off"
    depends_on:
      - "spitfire-primary"
    excludes: []
  - name: "bf109-secondary"
    source: "/mnt/backup/1/bf109/current/"
    dest: "/mnt/backup/2/bf109"
    copies: 30
    mount: "/mnt/backup/2"
    run: "off"
    depends_on:
      - "bf109-primary"
    excludes: []
